import { Link } from "react-router-dom";
import thumbnail from './images/capt_moroni.jpg';
import data from "./speaker_data.json";

const SpeakerListShort = ( ) => {
  const old_speakers = [
    { name: "Abinadi", link: "abinadi", id: 1, year: "200BC-148BC", word_count: 2075, description: "Abinadi knew King Noah would execute him for condemning the wickedness of the people and prophesying of their captivity (Mosiah 13:10). When the king offered Abinadi a chance to be set free if he would take back what he said, Abinadi faithfully and boldly refused. He had such great faith that he was willing to obey the Lord’s commands even if it meant he would die. At the time of his execution, it appeared that Abinadi had not made much of a difference; however, one individual, Alma, actually listened to him. Alma continued preaching Abinadi’s words to the people and eventually established the Church of God among the Nephites, so Abinadi’s death was not in vain.",fact: "", img: "none"},
    { name: "Alma the Younger", link: "alma-the-younger", id: 2, year: "144BC-73BC", word_count: 19981, description: "Alma, Son of Alma, was probably born at about the time his father was converted to the Gospel by the words of Abinadi, which means Alma was an adult when he and the sons of Mosiah rebelled against the Church and were subsequently converted to the Gospel after being visited by an Angel of the Lord. Alma’s conversion was evident through his commitment to watch over the Church and preach the Gospel. In fact, Alma gave up his position as Chief Judge over the Nephites in order to dedicate his time solely to the ministry (Alma 4:20). In addition to preaching throughout the land, Alma confronted both Nehor and Korihor, the anti-Christs. He also led the Nephites in battle against the Amlicites and revealed, by the Spirit of Prophecy, Lamanite positions to both Captain Zoram and Captain Moroni to help them gain tactical advantages over the Lamanites (Alma 16:5-6; 43:23-24).", fact: "Did You Know that in nearly all of Alma’s sermons contain allusions to his experience with the angel and his conversion?", img: "none"},
    { name: "Ammon", link: "ammon", id: 3, year: "130BC-60BC", word_count: 197, description: "Ammon was so dedicated to preaching the Gospel that he rejected his right to be king in order to lead a fourteen-year mission to the Lamanites. Within days of starting his mission, Ammon was taken before King Lamoni who, apparently knowing that Ammon was of royal heritage, offered to give Ammon one of his daughters to marry. But Ammon was committed to the work and volunteered to be Lamoni’s servant instead. Ammon’s service and courage at the water of Sebus led not only to the conversion of Lamoni and his family, but eventually to the conversion of several Lamanite cities.", fact: "Did you know that the Lamanites’ dramatic conversion reminded Ammon of his own?", img: "none"},
    { name: "Amulek", link: "amulek", id: 4, year: "130BC-60BC", word_count: 3164, description: "Amulek was a rich and popular Nephite living in the city of Ammonihah when an angel commanded him in a vision to receive Alma the Younger into his home. Alma helped Amulek grow strong in the faith, and they served together as missionary companions, but Amulek’s faith was soon put to the test. Because he preached the word of God to the people, Amulek was thrown in prison, his father and friends rejected him, and his wife and children were presumably burned alive with the other believers in Ammonihah. Despite these overwhelming hardships, Amulek remained faithful, and after being abused in prison for a long time, the Lord miraculously freed Amulek and Alma from their oppressors. Amulek continued to preach the Gospel and build up the Church throughout the land as Alma’s companion.", fact: "Did you know Amulek is the only speaker in the Book of Mormon to use the word “charitable” (Alma 34:29)?", img: "none"},
    { name: "Benjamin", link: "benjamin", id: 5, year: "200BC-121BC", word_count: 4219, description: "Benjamin was a righteous prophet and king of the Nephites. He fought with the Sword of Laban in a serious war against the Lamanites some 450 years after Nephi slew Laban with it! Benjamin also worked hard with other prophets to preach the Gospel to the people and rid the land of false prophets and false Christs until peace was finally established among the Nephites (W of M 1:12-18). A few years before his death, an angel of the Lord taught Benjamin about the Plan of Salvation and prophesied to him about the life and mission of Jesus Christ. Benjamin included this experience in a sermon he gave to the people from the temple.", fact: "Did you know that King Benjamin’s teachings focusing on Christ, kingship, and serving others may have been given in order to help his people avoid the kinds of conflict and contentions which they had experienced earlier in his reign?", img: "none"},
    { name: "Captain Moroni", link: "captain-moroni", id: 6, year: "100BC-56BC", word_count: 3067, description: "Most of Captain Moroni’s adult life was spent defending the Nephites against the Lamanites. He was only twenty-five years old when he was appointed chief captain of the Nephite armies, and he was responsible for many astounding victories over the Lamanites due to his revolutionary defensive tactics and striking military strategies. Moroni was also well-read in scripture and prophecy, and his faith and dedication to the Lord inspired him to raise the Title of Liberty. In fact, Moroni received many revelations from the Lord that instructed him how to protect the Nephites from both oppression and tyranny. He not only defended the Nephites against numerous attempted Lamanite conquests, but he also stopped four different rebellions to destroy the freedom of the Nephites. Moroni appears to have died before reaching the age of fifty, which may have been caused by the many wounds he was recorded to have received in battle.", fact: "Did you know that Moroni uses the word “religion” more than any other speaker in the Book of Mormon?", img: "none"},
    { name: "Giddianhi", link: "giddianhi", id: 7, year: "30BC-19AD", word_count: 499, description: "Giddianhi was the evil leader of the Gadianton robbers when Lachoneus was chief judge of the Nephites. Giddianhi told Lachoneus that unless the Nephites entirely surrendered to the Gadianton robbers, they would attack the Nephites the following month and completely destroy them. Lachoneus didn’t surrender, but Giddianhi didn’t attack the Nephites the following month like he said he would. In fact, Giddianhi didn’t lead his forces against the Nephites for over two years! During that time, the Nephites were able to prepare themselves to fight against Giddianhi, so when he finally attacked them, they beat his army back so badly that Giddianhi and countless other robbers were killed.", fact: "Did you know that Giddianhi is the only Book of Mormon speaker to use the word “noble”?", img: "none"},
    { name: "Helaman", link: "helaman", id: 8, year: "125BC-57BC", word_count: 4966, description: "Helaman was a powerful and faithful leader in the Church, but he appears to have had no previous military experience when the 2,000 stripling warriors asked him to lead them in battle. These faithful young men didn’t want a seasoned war veteran to lead them – they wanted a prophet of the Lord. Remarkably, Helaman accepted their request, and he led his little army, though entirely inexperienced, with perfect success. By the power of God, not one of Helaman’s young soldiers was killed during their many years of fighting, and Helaman and his army won every single battle they fought in!", fact: "Did You Know Helaman words suggest he was familiar with and alluded to military texts such as the book of Joshua on the plates of brass to teach the importance of faithfulness and obedience to God.", img: "none"},
    { name: "Jacob", link: "jacob", id: 9, year: "595BC-495BC", word_count: 8428, description: "Jacob appears to have lived to be about one hundred years old. He was born in the wilderness at about the same time his older brothers started having children (1 Nephi 17:1), and he was still young when his family sailed across the ocean to the promised land (1 Nephi 18:19). Jacob was exceedingly faithful and saw the Lord while he was still in his youth (2 Nephi 2:3-4; 11:3), and he was also faithful to his brother, Nephi. As a result of Jacob’s steadfastness, Nephi entrusted him with the Small Plates, upon which Jacob wrote his book. In his old age, Jacob confronted the anti-Christ Sherem, and by the word of Jacob, Sherem was struck and ultimately killed by the power of God.", fact: "Did you know Jacob’s words often reflect his calling as a priest in the temple? His words also show an ability to paint vivid images and suggest he was a man whose emotions may at times have been close to the surface.", img: "none"},
    { name: "Korihor", link: "korihor", id: 10, year: "110BC-74BC", word_count: 680, description: "Korihor was an anti-Christ who preached to the Nephites against the existence of God. The government had no legal authority to prosecute Korihor for his beliefs, but the Church had authority to judge its members for sins they committed (Mosiah 26:29-36). For that reason, Korihor was taken before the high priests of the lands of Jershon and Gideon and then finally before Alma the Younger, who was high priest over the whole Church. Korihor demanded a sign from Alma to prove the existence of God, so in the name of God, Alma struck Korihor dumb. Only then did Korihor confess that the devil appeared to him in the form of an angel and told him to lie to the people.", fact: "Did you know that Korihor is the only Book of Mormon speaker to use the phrase “the foolish traditions of your fathers”?", img: "none"},
    { name: "Lehi", link: "lehi", id: 11, year: "645BC-580BC", word_count: 4613, description: "Lehi was a prophet of God who was probably in his forties when he was commanded by the Lord in a dream to lead his family towards the promised land. Lehi was often directed by the Lord in dreams, and he also had many visions including a vision in which he saw the Lord, a vision of the Tree of Life, and a vision that revealed the destruction of Jerusalem. Lehi wrote a record of his life, dreams, and visions called the Book of Lehi which was included in the 116 lost manuscript pages of the Book of Mormon; fortunately, Lehi’s son, Nephi, included an abridgment of the Book of Lehi in his own record (1 Nephi 1:16-17; 10:1).", fact: "Did you know that Lehi is the only Book of Mormon prophet to refer to the Messiah as the great Mediator?", img: "none"},
    { name: "Mormon", link: "mormon", id: 12, year: "310AD-390AD", word_count: 97813, description: "Mormon was so large in stature that the Nephites placed him as the commander of their armies when he was only sixteen years old (Mormon 2:1-2), and he continued to lead the armies of the Nephites off and on until the Nephites were finally defeated at Cumorah. At one point, Mormon refused to lead the Nephite armies because of their wickedness, but he was such an outstanding leader that the Nephites considered him to be their only hope of survival and begged him to lead them again. Mormon was entrusted with the sacred records of the Nephites when he was ten years old, he was visited of the Lord when he was only fifteen, and he was eventually ordained as one of the Disciples of Jesus Christ (3 Nephi 5:13). Mormon lived after the final battle at Cumorah in about 385 AD long enough to write at least what now consists of Mormon 6-7, but sometime between the final battle and about 400 AD, Mormon was killed by the Lamanites, making Moroni the last surviving Nephite.", fact: "Did you know that when Mormon uses the adjective “great” the most common object is joy?", img: "none"},
    { name: "Moroni, Son of Mormon", link: "moroni", id: 13, year: "340AD-425AD", word_count: 19000, description: "Moroni was very concerned that the Book of Mormon would be rejected by future generations, in particular because of the Nephites’ weakness in writing (Ether 12:23-25). The Lord visited Moroni and spoke to him face to face, as one man speaks to another (Ether 12: 39), and the Lord showed him the future generations of the earth when the Book of Mormon would come forth (Mormon 8:34-35), which comforted Moroni. In addition to his words now contained in the Book of Mormon, Moroni wrote the vision of the Brother of Jared in the sealed portion of the plates, which reveals “all things from the foundation of the world unto the end thereof” (2 Nephi 27:10) and of which Moroni commented, “there never were greater things made manifest” (Ether 4:4-6).", fact: "Did you know that Moroni is the only Nephite prophet to use the name Jehovah?", img: "none"},
    { name: "Mosiah", link: "mosiah", id: 14, year: "154BC-91BC", word_count: 1178, description: "Mosiah was not only a great Nephite king, but also a great prophet of God. As a seer, he had the divine gift to translate the record of the Jaredites left by the prophet Ether. As a prophet, he received revelations from the Lord and gave Alma authority to establish the church of God throughout the land. Mosiah also received, by revelation, the laws he created as king (Hel 4:22). He united the people in an era of peace, and before his death he established the Reign of the Judges. This new form of government allowed the people to elect their leaders democratically to judge the people based on the righteous laws of Mosiah.", fact: "Did you know that Mosiah is the only Book of Mormon speaker who refers to God as the “all-wise Creator”?", img: "none"},
    { name: "Nephi, Son of Helaman", link: "nephi-son-of-helaman", id: 15, year: "75BC-1BC", word_count: 2256, description: "Nephi taught with such great power and authority that in a single year, he and his brother Lehi converted most of the Lamanite civilization to the Gospel! Like Alma the Younger, Nephi gave up his position as chief judge to dedicate his life to preaching the Gospel. At one point, the Spirit physically carried Nephi from place to place until he taught all the Nephites (Hel 10:16-17). The Lord trusted Nephi so much that He gave Nephi the sealing power to perform whatever miracles were needed, and Nephi used this power to start and end a great famine that caused the people to repent.", fact: "Did you know that at Nephi cites more prophets from the brass plates in a single discourse than any other Book of Mormon speaker?", img: "none"},
    { name: "Nephi, Son of Lehi", link: "nephi-son-of-lehi", id: 16, year: "615BC-540BC", word_count: 27366, description: "Nephi was not only large enough in stature to break his steel bow, but also faithful enough to become the spiritual leader of his family as they journeyed through the Arabian wilderness. Nephi received many revelations from the Lord while still in his youth, including the interpretation of Lehi’s vision of the Tree of Life, in which Nephi also saw the mortal ministry of Christ and much of the history of the world. The Lord also showed Nephi how to build a ship, which Nephi faithfully built and navigated to carry his family to the promised land. Nephi continued to exercise great faith and dedication to the Lord to the end of his life. Before his death, he built a temple and provided means to support and protect his people, and he began the record of the Nephites that would be passed down through the generations a thousand years to Mormon and Moroni.", fact: "Did you know that Nephi uses the title ‘Lamb of God’ for Christ more than any other Nephite prophet?", img: "none"},
    { name: "Pahoran", link: "pahoran", id: 17, year: "125BC-52BC", word_count: 817, description: "Pahoran became chief judge while the Nephites were in the middle of a very serious war against the Lamanites. As if things were not bad enough with the Lamanites, an uprising occurred in Zarahemla that forced Pahoran to flee the city and threatened the safety and liberty of the nation. When Captain Moroni found out about the uprising, he assembled an army and fought with Pahoran against the rebels to take back Zarahemla. After defeating the rebels, Pahoran left the security of Zarahemla and personally led an army in the war against the Lamanites, assisting Moroni in two important victories that helped the Nephites finally win the war.", fact: "Did you know that Pahoran was as committed to freedom from sin as he was to freedom from kings?", img: "none"}


  ];
  const speakers = data.speakers

  return ( 
    
    <div className="speaker-list-short">
      
      {speakers.map((speaker) => (
        <div className="blog-preview" key={speaker.id}>
          <Link to={ '/speakers/' + speaker.link }>
            <h2>{ speaker.name }</h2>
            <img src={thumbnail} alt="" />
          </Link>



        </div>
      ))}
    </div>
      
   );
}
 
export default SpeakerListShort;